### ISSUE TITLE
Alert Not Working After Livewire session()->flash()

### ISSUE THREAD

**Issue by MusahMusah** [uyanik13/Laravel-7-8-Sweet-Alert-#1]
- Package Version: #.#.# 9999999-dev
- Laravel Version: #.#.# 8.12

### Steps To Reproduce:

**Comment by uyanik13** [comment]
Sorry for that. I just fixed livewire alert. You can update the package and please look at the readme file for livewire usage.

**Comment by MusahMusah** [comment]
Thanks will update package and try it out again...
